// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATlCu_V6oqsZ0fA-KAmpuDH9H3CaNHxqU',
    appId: '1:334189383330:web:00a155b1a7f779669e51fb',
    messagingSenderId: '334189383330',
    projectId: 'medsync-01',
    authDomain: 'medsync-01.firebaseapp.com',
    storageBucket: 'medsync-01.appspot.com',
    measurementId: 'G-12Y0EDWKK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQULgr1dmGxEgKTeVSyDmcOnLPdOOtkdg',
    appId: '1:334189383330:android:8567c09d20fcdc929e51fb',
    messagingSenderId: '334189383330',
    projectId: 'medsync-01',
    storageBucket: 'medsync-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu1Ib9Be8RGc8Pf9bFMqhhmVwTdUZUA4Q',
    appId: '1:334189383330:ios:6c4b07262cb571379e51fb',
    messagingSenderId: '334189383330',
    projectId: 'medsync-01',
    storageBucket: 'medsync-01.appspot.com',
    iosBundleId: 'com.example.medsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu1Ib9Be8RGc8Pf9bFMqhhmVwTdUZUA4Q',
    appId: '1:334189383330:ios:6c4b07262cb571379e51fb',
    messagingSenderId: '334189383330',
    projectId: 'medsync-01',
    storageBucket: 'medsync-01.appspot.com',
    iosBundleId: 'com.example.medsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATlCu_V6oqsZ0fA-KAmpuDH9H3CaNHxqU',
    appId: '1:334189383330:web:bf6cd71ecd7fd4e79e51fb',
    messagingSenderId: '334189383330',
    projectId: 'medsync-01',
    authDomain: 'medsync-01.firebaseapp.com',
    storageBucket: 'medsync-01.appspot.com',
    measurementId: 'G-456S51W4NG',
  );

}